version: '2.0'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: df/php/Dockerfile
    image: php:8.1.7-cli
    volumes:
      - .:/var/www/html
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "8443:443"
    networks:
      - app-network

  #MySQL Service
  db:
    build:
      context: .
      dockerfile: df/db/Dockerfile
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge